#pragma config(Sensor, S1,     ,               sensorEV3_IRSensor, modeEV3IR_Remote)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int cpuup;
int cpudwn;
int plup;
int pldwn;
int posxleft;
int posxright;
int posytop
int posybot;
int speedx;
int speedy
bool win;
bool lose;
bool ready;

task main()
{
	win = false
	lose = false
	ready = false
	cpuup = 30;
	cpudwn = 60;
	plup = 30;
	pldwn = 60;
	posxleft = 84
	posxright = 92
	posytop = 59
	posybot = 67
	speedx = 1
	speedy = 1

	while(ready == false)
	{
		if (win == false)
		{
			if (lose == false)
			{
				displayCenteredBigTextLine(4, "ARE YOU READY??")
			}
		}
		if (win == true)
		{
			displayCenteredBigTextLine(4, "WINNER!")
			delay(5000)
		}
		if (lose == true)
		{
			displayCenteredBigTextLine(4, "GET SHREKT KID")
			delay(5000)
		}
		if (getButtonPress(buttonEnter) == 1)
		{
			ready =true
		}
	}



	while(ready == true)
	{
		while(win == false)
		{
			while(lose == false)
			{
				eraseDisplay()
				drawLine(10,cpudwn,10,cpuup);
				drawLine(170,pldwn,170,plup);
				drawEllipse(posxleft ,posytop ,posxright,posybot )
				posxleft = posxleft + speedx
				posxright = posxright+ speedx
				posytop = posytop + speedy
				posybot = posybot + speedy
				delay(20)
				//setPixel(posx,posy)
				//clearPixel(posx-speed,posy-speed)
				//find a way to program in movement that can move in different directions


				if (getButtonPress(buttonUp) == 1)
				{
					plup++;
					clearPixel(170,plup-1);
					pldwn++;


				}

				if (getButtonPress(buttonDown) == 1)
				{
					plup--;
					clearPixel(170,pldwn+1);
					pldwn--;


				}
				if (posytop > cpuup)
				{
					cpuup = cpuup + 2
					cpudwn = cpudwn + 2
					clearPixel(10,cpuup-1);
				}
				if (posybot < cpudwn)
				{
					cpuup = cpuup - 2
					cpudwn = cpudwn - 2
					clearPixel(10,cpudwn+1);

				}
				if(posxleft <= 0)
				{
					win = true
					ready = false
				}
				if (posxright >= 177)
				{
					lose = true
					ready = false
				}
				//program messages for winning and losing.
				if(posxright == 171)

				{
					if (plup<posybot)
					{
						if (posytop<pldwn)
						{
							speedx = -speedx
						}
					}
				}
				if(posxleft == 11)
				{
					if (cpuup<=posytop)
					{
						if (posybot<=cpudwn)
						{
							speedx = -speedx
						}
					}
				}
				if(posytop == 0)
				{
					speedy = -speedy
				}
				if(posybot == 127)
				{
					speedy = -speedy
				}
				if (pldwn == 127)
				{
					pldwn = 127
					plup = 97
				}
				if (plup == 0)
				{
					plup = 0
					pldwn = 30
				}
			}
			displayCenteredBigTextLine(4, "GET SHREKT KID")
			delay(5000)
		}
		displayCenteredBigTextLine(4, "WINNER!")
		delay(5000)


	}
}
